### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by yurtpage** [mwarning/trigger#84]
You can use the Weblate.org as in Meshanger but it needs for some moderation (that should pass).
Alternatively there is another Weblate instance on Codeberg https://translate.codeberg.org/ that doesn't have a moderation but it won't send a PR on the GitHub.
The Crowdin also free for FOSS https://crowdin.com/page/open-source-project-setup-request
In my experience it has a very good auto-translation and especially good for large texts. But for the app the Weblate should be enough.

If you decide to use the Crowdin then you may try this `crowdin.yml`:

```yaml
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /metadata/en-US/*.txt
    translation: /metadata/%locale%/%original_file_name%
```

Related #19
